stages:
  - compile

image: gumjoe/wacc-ci-scala:slim

compile:
  stage: compile
  before_script:
    - echo "Compiling..."
  script:
    - scala compile .
  after_script:
    - echo "Compilation done."