stages:
  - compile
  - test

image: gumjoe/wacc-ci-scala:slim

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .bsp/
    - .scala-build/

compile:
  stage: compile
  before_script:
    - echo "Compiling..."
  script:
    - scala compile .
  after_script:
    - echo "Compilation done."

test:
  stage: test
  before_script:
    - echo "Running Tests..."
  script:
    - scala test .
  after_script:
    - echo "Testing done."
    - echo "good boy"