stages:
  - compile
  - test

image: gumjoe/wacc-ci-scala:slim

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .bsp/
    - .scala-build/

compile:
  stage: compile
  before_script:
    - echo "Compiling..."
  script:
    - scala compile .
  after_script:
    - echo "Compilation done."

test:
  stage: test
  before_script:
    - echo "Installing dependencies..."
    - apt-get update && apt-get install -y gcc python3 python3-pip python3-yaml
    - echo "Dependencies installed."
    - echo "Running Tests..."
  script:
    - python3 runSelectedTests.py
  after_script:
    - echo "Testing done."