stages:
  - compile
  - test

image: gumjoe/wacc-ci-scala:slim

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - target/
    - .bsp/
    - .scala-build/

compile:
  stage: compile
  before_script:
    - echo "Compiling..."
  script:
    - scala compile . --server=false
  after_script:
    - echo "Compilation done."

test:
  stage: test
  before_script:
    - echo "Installing dependencies..."
    - apt-get update && apt-get install -y gcc
    - echo "Running tests..."
  script:
    - scala test . --server=false
  after_script:
    - echo "Testing done."
    - echo "good boy"