package wacc.testUtils

val testSettings = scala.collection.immutable.HashSet(
    "prog",
    "expr_test",
    "atom",
    "unary_oper",
    "binary_oper",
    "array_elem",
    "type_parent",
    "type_base",
    "type_array",
    "type_pair",
    "func",
    "param",
    "stmt",
    "lvalue",
    "rvalue",
    "pair_elem",
    "array_literal",
    "syntax_integration",
    "rename_if",
    "rename_codeblock",
    "rename_decl",
    "rename_expr",
    "rename_func",
    "rename_prog",
    "rename_while",
    "types_test",
    "semantic_integration",
    "format_operand",
    "format_reg",
    "format_mem_offset",
    "format_offset",
    "format_arithmetic_op_test",
    "format_branching_test",
    "format_memory_ops_test",
    "format_function_ops_test",
    "format_cond_test",
    "format_prog_test",
    "format_headers_test",
    "format_data_test",
    "format_function_test",
    // "integration_exit",
    // "integration_skip",
    // "integration_advanced",
    // "integration_array",
    // "integration_expressions",
    // "integration_nested_functions",
    // "integration_simple_functions",
    // "integration_if",
    // "integration_IO_all",
    // "integration_IO_print",
    // "integration_IO_read",
    // "integration_pairs",
    // "integration_runtimeErr_arrayOutOfBounds",
    // "integration_runtimeErr_badChar",
    // "integration_runtimeErr_divideByZero",
    // "integration_runtimeErr_integerOverflow",
    // "integration_runtimeErr_nullDereference",
    // "integration_scope",
    // "integration_sequence",
    // "integration_variables",
    // "integration_while"
)