package wacc.testUtils

val testSettings = scala.collection.mutable.HashMap(
    "syntax.prog" -> true,
    "syntax.expr" -> true,
    "syntax.atom" -> true,
    "syntax.unary_oper" -> true,
    "syntax.binary_oper" -> true,
    "syntax.array_elem" -> true,
    "syntax.type_parent" -> true,
    "syntax.type_base" -> true,
    "syntax.type_array" -> true,
    "syntax.type_pair" -> true,
    "syntax.func" -> true,
    "syntax.param" -> true,
    "syntax.stmt" -> true,
    "syntax.lvalue" -> true,
    "syntax.rvalue" -> true,
    "syntax.pair_elem" -> true,
    "syntax.array_literal" -> true,
    "syntax.syntax_integration" -> true,
    "semantic.rename_if" -> true,
    "semantic.rename_codeblock" -> true,
    "semantic.rename_decl" -> true,
    "semantic.rename_expr" -> true,
    "semantic.rename_func" -> true,
    "semantic.rename_prog" -> true,
    "semantic.rename_while" -> true,
    "semantic.types_test" -> true,
    "semantic.semantic_integration" -> true,
    "formatting.format_operand" -> true,
    "formatting.format_reg" -> true,
    "formatting.format_mem_offset" -> true,
    "formatting.format_offset" -> true,
    "formatting.format_arithmetic_op_test" -> true,
    "formatting.format_branching_test" -> true,
    "formatting.format_memory_ops_test" -> true,
    "formatting.format_function_ops_test" -> true,
    "formatting.format_cond_test" -> true
)