package wacc.testUtils

val testSettings = scala.collection.mutable.HashMap(
    "prog" -> true,
    "expr_test" -> true,
    "atom" -> true,
    "unary_oper" -> true,
    "binary_oper" -> true,
    "array_elem" -> true,
    "type_parent" -> true,
    "type_base" -> true,
    "type_array" -> true,
    "type_pair" -> true,
    "func" -> true,
    "param" -> true,
    "stmt" -> true,
    "lvalue" -> true,
    "rvalue" -> true,
    "pair_elem" -> true,
    "array_literal" -> true,
    "syntax_integration" -> true,
    "rename_if" -> true,
    "rename_codeblock" -> true,
    "rename_decl" -> true,
    "rename_expr" -> true,
    "rename_func" -> true,
    "rename_prog" -> true,
    "rename_while" -> true,
    "types_test" -> true,
    "semantic_integration" -> true,
    "format_operand" -> true,
    "format_reg" -> true,
    "format_mem_offset" -> true,
    "format_offset" -> true,
    "format_arithmetic_op_test" -> true,
    "format_branching_test" -> true,
    "format_memory_ops_test" -> true,
    "format_function_ops_test" -> true,
    "format_cond_test" -> true
)